### PR TITLE
Multiple Fieldsets of Type `Tab` per Form

### PR DESCRIPTION
**Pull request by marcus-at-localhost**
Groups fieldset tabs as they appear in a form.
Needs plain fielsets `'k' => ['type' => 'fieldset', 'label' => 'Break out tabs'],` to break out of the tabs.
Made it work without updating jquery and made it future proof.
```
// https://stackoverflow.com/a/17809461/814031
if(!$.fn.addBack){
	$.fn.addBack = $.fn.andSelf;
}
```

Description and proposal here: https://github.com/daylightstudio/FUEL-CMS/issues/569

### CODE REVIEW

**Comment by daylightstudio** [comment]
Does this change also require the update to jQuery? If so, can you include that in the pull request too?

**Comment by marcus-at-localhost** [comment]
@daylightstudio no jquery update is needed here, I check for the used modern method `$.fn.addBack` and fall back to deprecated method `$.fn.andSelf` so it should work now with jq 1.7 and in the future.

**Comment by daylightstudio** [comment]
Great. Will take a look.

**Comment by daylightstudio** [comment]
So the only thing I'm seeing is that the open tabbed state being saved in the cookie is not being specific to each tab group. So for example, say you have tabs A and B located at the top, then tabs C and D located in the middle of your form, clicking on tab B will set the open state for both B and D to be open (saves the index of the tabs and in this case the index would be 1 for both B and D).

**Comment by marcus-at-localhost** [comment]
> So the only thing I'm seeing is that the open tabbed state being saved in the cookie is not being specific to each tab group.

of course :) I'll see that I can fix that. I assume instead of the index I have save a compound key made from outer loop (group) `i + '_' + idx` and inner loop (tab).
Thanks

**Pull request merged**
