### PR TITLE
Move helper function PHPDocs inside 'function_exists' checks to help IDEs

### PR DESCRIPTION
**Pull request by martynassateika**
Moves the PHPDoc comments inside helper files so they appear inside the `if (!function_exists...)` checks.

This allows IDEs to link the PHPDocs to the functions. Developers can then be immediately notified by the IDE if they're using a helper function incorrectly (passing wrong parameters, etc).

Moreover, this helped me uncover some errors in the PHPDocs themselves.

Lastly, some missing delimiter comments `// -------` have been added.

Best to go through this MR commit by commit to better see what changed.

### CODE REVIEW

**Comment by martynassateika** [comment]
Welp, looks like I messed up the whitespacing again..

By the way, the `fuel_helper` class has no `function_exists` checks. Shouldn't they be added there, too?

**Comment by martynassateika** [comment]
Also @daylightstudio what do you have your tab size set to?

**Comment by daylightstudio** [comment]
For fuel_helper, the function_exists was never added because those functions were never really meant to be something you could overwrite but adding them wouldn't hurt. For tab size, it's set to 4 spaces.

**Comment by martynassateika** [comment]
Argh, I don't get why Github is showing changes differently than PhpStorm.

Github: https://github.com/daylightstudio/FUEL-CMS/pull/445/commits/34f4c40e32e3749e7c482f32169a4ea70098c755#diff-d151d02afc455c5496f4f23c2847757eR132

Phpstorm:
phpstorm-output

According to Phpstorm it'd take two TABs to line up the three `@param`s.

**Comment by martynassateika** [comment]
Added checks for functions in `fuel_helper`.

**Pull request merged**
