### PR TITLE
Remove duplicate SERVER_NAME

### PR DESCRIPTION
**Pull request by olivierlacan**
I doubt we need two of these.

### CODE REVIEW

**Comment by daylightstudio** [comment]
Not sure I understand this pull request.

**Comment by olivierlacan** [comment]
The PR diff doesn’t show you the exact same assignment happens a few lines above: https://github.com/daylightstudio/FUEL-CMS/pull/605/files#diff-7413d6453f901e939bbd840c8f0d1c7b20c2ca0e7f71741e4e07c6cf036f16c0L27

**Comment by daylightstudio** [comment]
I see. I missed that when I checked. I'm going to make that change in the develop branch first and push so will close this out. Thanks for the report!

**Comment by olivierlacan** [comment]
@daylightstudio Thanks. I'll try to remember to make PRs against `develop` but FYI it's trivial to switch the [base branch of any PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request).

I'm curious if you're planning on releasing a patch release with the changes in `develop` sometime soon. I'm trying to bring a project up from PHP 7.x to 8.x still all the changes involving 8.x would surely be helpful. Thanks.

**Comment by daylightstudio** [comment]
I currently don't have a timeline for the next release but the current `master` branch should be compatible with PHP 8.1x (minus a few updates). You can also just pull in the `develop` branch.

**Pull request closed without merging**
